name: deploy
on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["amd64"]
        os: ["linux", "windows"]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - name: build and release
        uses: onichandame/go-release-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goarch: ${{ matrix.arch }}
          goos: ${{ matrix.os }}
        env:
          CGO_ENABLED: 0
