name: deploy
on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["amd64"]
        os: ["linux", "windows"]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - name: build and release
        uses: wangyoucao577/go-release-action@v1.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_flags: '-ldflags "-linkmode external -extldflags -static"'
          goarch: ${{ matrix.arch }}
          goos: ${{ matrix.os }}
