name: deploy
on: release
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["amd64"]
        os: ["linux", "windows"]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - name: build and release
        uses: ngs/go-release.action@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOARCH: ${{ matrix.arch }}
          GOOS: ${{ matrix.os }}
